Vagrant::Config.run do |config|
  config.vm.box = "lucid32"
  config.vm.box_url = "http://files.vagrantup.com/lucid32.box"
  config.vm.network :hostonly, "10.0.0.2"
  config.vm.forward_port 27017, 27017
  config.vm.share_folder "apache", "/home/vagrant/apache", "../apache"
  config.vm.share_folder "wheel", "/home/vagrant/wheel", "../wheel"
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "."
    puppet.manifest_file  = "puppet.pp"
  end
end